Update update-year.yml
Test verification

diff --git a/.github/workflows/update-year.yml b/.github/workflows/update-year.yml
--- a/.github/workflows/update-year.yml
+++ b/.github/workflows/update-year.yml
@@ -16,6 +16,12 @@ jobs:
           #  echo "Error: This workflow cannot be run from the template repository."
      #       exit 1
     #      fi
+      - name: Check for Token Secret
+        run: |
+          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
+            echo "Error: GH_TOKEN secret is not set."
+            exit 1
+          fi
       - name: Check Year Format
         run: |
           if echo "${{ github.event.inputs.aoc_year }}" | grep -E -q '^[0-9]{4}$'; then
