Update update-year.yml

diff --git a/.github/workflows/update-year.yml b/.github/workflows/update-year.yml
--- a/.github/workflows/update-year.yml
+++ b/.github/workflows/update-year.yml
@@ -12,11 +12,11 @@ jobs:
     steps:
     - name: Check Year Format
       run: |
-          echo "year = ${{ github.event.inputs.aoc_year }}"
-          if [[ ! ${{ github.event.inputs.aoc_year =~ ^[0-9]{4}$ }} ]]; then
-            echo "Error: Invalid year format. Please provide a valid 4-digit year."
-            exit 1
-          fi
+        echo "year = ${{ github.event.inputs.aoc_year }}"
+        if [[ ! ${{ github.event.inputs.aoc_year =~ ^[0-9]{4}$ }} ]]; then
+          echo "Error: Invalid year format. Please provide a valid 4-digit year."
+          exit 1
+        fi
     - uses: actions/checkout@v3
     - name: Update README.md
       run: |
