Update update-year.yml

diff --git a/.github/workflows/update-year.yml b/.github/workflows/update-year.yml
--- a/.github/workflows/update-year.yml
+++ b/.github/workflows/update-year.yml
@@ -10,10 +10,14 @@ jobs:
   update-year:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Update Advent of Code year
+    - name: Check Year Format
       run: |
-        echo "year = ${{ github.event.inputs.aoc_year }}" +
+          echo "year = ${{ github.event.inputs.aoc_year }}"
+          if [[ ! ${{ github.event.inputs.aoc_year =~ ^[0-9]{4}$ }} ]]; then
+            echo "Error: Invalid year format. Please provide a valid 4-digit year."
+            exit 1
+          fi
+    - uses: actions/checkout@v3
     - name: Update README.md
       run: |
         find . -name 'README.md' | xargs sed -i 's/{year}/'${{ github.event.inputs.aoc_year }}'/g'
